### ISSUE TITLE
AssertionError on import (wrong keccak function?) OSX, python 2.7.13

### ISSUE THREAD

**Issue by pinheadmz** [pipermerriam/ethereum-utils#8]
Not sure what I've got wrong here:

```
~ $ pip install ethereum-utils
Requirement already satisfied: ethereum-utils in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: pysha3>=0.3 in /usr/local/lib/python2.7/site-packages (from ethereum-utils)
~ $ python
Python 2.7.13 (default, Apr  4 2017, 08:44:49) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import eth_utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/eth_utils/__init__.py", line 5, in <module>
    from .abi import (  # noqa: F401
  File "/usr/local/lib/python2.7/site-packages/eth_utils/abi.py", line 3, in <module>
    from .crypto import keccak
  File "/usr/local/lib/python2.7/site-packages/eth_utils/crypto.py", line 18, in <module>
    assert keccak('') == b"\xc5\xd2F\x01\x86\xf7#<\x92~}\xb2\xdc\xc7\x03\xc0\xe5\x00\xb6S\xca\x82';{\xfa\xd8\x04]\x85\xa4p"  # noqa: E501
AssertionError
```

**Comment by pinheadmz** [comment]
OK! I needed to run `python3` not `python`
